### ISSUE TITLE
Error in booking: slice bounds out of range [:25] with length 12

### ISSUE THREAD

**Issue by fifiteen82726** [bthuilot/book-it#1]
First of all, great project.

Here is what I've done

```shell
export RESY_EMAIL="email"
export RESY_PASSWORD="pwd"
go build -o book-it
./book-it -v 64154 -d 05/17/23 -t 07:30PM -s 3600 -p 2 --include-types "Lounge Seating"
```

Test resy: https://resy.com/cities/ny/kyu?date=2023-05-17&seats=2

### Error 
```shell
./book-it -v 64154 -d 05/17/23 -t 07:30PM -s 3600 -p 2 --include-types "Lounge Seating"
INFO[0000] constructing Resy client
panic: runtime error: slice bounds out of range [:25] with length 12

goroutine 1 [running]:
github.com/bthuilot/book-it/pkg/resy.(*client).passwordAuth(0x140001205c0)
	/Users/codchang/Desktop/Coda/book-it/pkg/resy/auth.go:45 +0x248
github.com/bthuilot/book-it/pkg/resy.(*client).refreshToken(...)
	/Users/codchang/Desktop/Coda/book-it/pkg/resy/auth.go:38
github.com/bthuilot/book-it/pkg/resy.NewClient()
	/Users/codchang/Desktop/Coda/book-it/pkg/resy/api.go:49 +0xdc
github.com/bthuilot/book-it/cmd.glob..func2(0x102da7200?, {0x1029b15fa?, 0xc?, 0xc?})
	/Users/codchang/Desktop/Coda/book-it/cmd/root.go:88 +0xc8
github.com/spf13/cobra.(*Command).execute(0x102da7200, {0x1400001e5c0, 0xc, 0xc})
	/Users/codchang/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x5b0
github.com/spf13/cobra.(*Command).ExecuteC(0x102da7200)
	/Users/codchang/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/codchang/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/bthuilot/book-it/cmd.Execute()
	/Users/codchang/Desktop/Coda/book-it/cmd/root.go:104 +0x28
main.main()
	/Users/codchang/Desktop/Coda/book-it/main.go:8 +0x1c
```

**Comment by fifiteen82726** [comment]
Another error

```
API endpoint returned 402 not 200: {"status": 402, "code": null, "message": "Payment Required", "data": {}}
```

**Comment by bthuilot** [comment]
@fifiteen82726 thanks for checking the project out!

The second one I have as a TODO already so will also get started on the password one and update this thread when the PR is merged in

**Comment by bthuilot** [comment]
closing this as i tested locally and should be all good to go now, thank you again for the report!
